name: Check code when push

on: 
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  check-code:
    name: Check code
    runs-on: windows-lastest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - run: npm install
      - run: npm run ci
